version: "2.2"
services:

        YingWater:
                image: yingwater:1.1
                build: .
                container_name: YingWater
                working_dir: /YingWater
                ports:
                        - "80:80"
                volumes:
                        - .:/YingWater
                command: gunicorn -c ./gunicorn.conf.py run:app
