"""add GbData table

Revision ID: 2ef689c4a89c
Revises: 37fd6ba85d13
Create Date: 2023-01-01 16:25:10.287760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef689c4a89c'
down_revision = '37fd6ba85d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GbData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('溶解氧', sa.Float(), nullable=False, comment='溶解氧'),
    sa.Column('高锰酸盐指数', sa.Float(), nullable=False, comment='高锰酸盐指数'),
    sa.Column('五日生化需氧量', sa.Float(), nullable=False, comment='五日生化需氧量'),
    sa.Column('氨氮', sa.Float(), nullable=False, comment='氨氮'),
    sa.Column('总磷', sa.Float(), nullable=False, comment='总磷'),
    sa.Column('等级', sa.Float(), nullable=False, comment='水质等级'),
    sa.Column('类型', sa.Float(), nullable=False, comment='1,分级标准;2,最佳投影向量'),
    sa.Column('is_use', sa.Float(), nullable=False, comment='1,是;0,否'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GbData_id'), 'GbData', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_GbData_id'), table_name='GbData')
    op.drop_table('GbData')
    # ### end Alembic commands ###
