"""yingdata add nullable

Revision ID: 37fd6ba85d13
Revises: 85f659c4aaef
Create Date: 2023-01-01 12:36:12.793503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37fd6ba85d13'
down_revision = '85f659c4aaef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('YingData', '溶解氧',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='溶解氧')
    op.alter_column('YingData', '高锰酸盐指数',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='高锰酸盐指数')
    op.alter_column('YingData', '五日生化需氧量',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='五日生化需氧量')
    op.alter_column('YingData', '氨氮',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='氨氮')
    op.alter_column('YingData', '总磷',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_comment='总磷')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('YingData', '总磷',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='总磷')
    op.alter_column('YingData', '氨氮',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='氨氮')
    op.alter_column('YingData', '五日生化需氧量',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='五日生化需氧量')
    op.alter_column('YingData', '高锰酸盐指数',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='高锰酸盐指数')
    op.alter_column('YingData', '溶解氧',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_comment='溶解氧')
    # ### end Alembic commands ###
