"""init database

Revision ID: 85f659c4aaef
Revises: 
Create Date: 2023-01-01 12:31:42.863052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f659c4aaef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', '监测点',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=False,
               comment='水库名称')
    op.alter_column('data', '测量时间',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment='测量时间',
               existing_nullable=False)
    op.alter_column('data', '水温',
               existing_type=mysql.FLOAT(),
               comment='水温',
               existing_nullable=True)
    op.alter_column('data', 'pH',
               existing_type=mysql.FLOAT(),
               comment='pH',
               existing_nullable=True)
    op.alter_column('data', '溶解氧',
               existing_type=mysql.FLOAT(),
               comment='溶解氧',
               existing_nullable=True)
    op.alter_column('data', '电导率',
               existing_type=mysql.FLOAT(),
               comment='电导率',
               existing_nullable=True)
    op.alter_column('data', '浊度',
               existing_type=mysql.FLOAT(),
               comment='浊度',
               existing_nullable=True)
    op.alter_column('data', '高锰酸盐指数',
               existing_type=mysql.FLOAT(),
               comment='高锰酸盐指数',
               existing_nullable=True)
    op.alter_column('data', '总磷',
               existing_type=mysql.FLOAT(),
               comment='总磷',
               existing_nullable=True)
    op.alter_column('data', '总氮',
               existing_type=mysql.FLOAT(),
               comment='总氮',
               existing_nullable=True)
    op.alter_column('data', '叶绿素',
               existing_type=mysql.FLOAT(),
               comment='叶绿素',
               existing_nullable=True)
    op.alter_column('data', '蓝绿藻',
               existing_type=mysql.FLOAT(),
               comment='蓝绿藻',
               existing_nullable=True)
    op.alter_column('data', '氨氮',
               existing_type=mysql.FLOAT(),
               comment='氨氮',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', '氨氮',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='氨氮',
               existing_nullable=True)
    op.alter_column('data', '蓝绿藻',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='蓝绿藻',
               existing_nullable=True)
    op.alter_column('data', '叶绿素',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='叶绿素',
               existing_nullable=True)
    op.alter_column('data', '总氮',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='总氮',
               existing_nullable=True)
    op.alter_column('data', '总磷',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='总磷',
               existing_nullable=True)
    op.alter_column('data', '高锰酸盐指数',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='高锰酸盐指数',
               existing_nullable=True)
    op.alter_column('data', '浊度',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='浊度',
               existing_nullable=True)
    op.alter_column('data', '电导率',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='电导率',
               existing_nullable=True)
    op.alter_column('data', '溶解氧',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='溶解氧',
               existing_nullable=True)
    op.alter_column('data', 'pH',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='pH',
               existing_nullable=True)
    op.alter_column('data', '水温',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='水温',
               existing_nullable=True)
    op.alter_column('data', '测量时间',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               comment=None,
               existing_comment='测量时间',
               existing_nullable=False)
    op.alter_column('data', '监测点',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='水库名称')
    # ### end Alembic commands ###
